[build]
  publish = "public"
  command = "npm run build"

[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200

[[redirects]]
  from = "/admin/config.yml"
  to = "/.netlify/functions/config"
  status = 200

[build.environment]
  NODE_VERSION = "16"

[functions]
  directory = "functions"
