[build]
  publish = "public"
  command = "npm install && npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "16"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["gray-matter", "@netlify/functions", "node-fetch"]
  included_files = ["content/**"]

# Netlify Identity is handled automatically by Netlify
[identity]
  enable = true
  invite_only = true

# Redirects
[[redirects]]
  from = "/#invite_token=*"
  to = "/admin/cms/#invite_token=:splat"
  status = 301
  force = true

# CMS at /admin/cms redirects
[[redirects]]
  from = "/admin/cms/config.yml"
  to = "/.netlify/functions/config"
  status = 200
  force = true

[[redirects]]
  from = "/admin/cms/*"
  to = "/admin/cms/index.html"
  status = 200

# Legacy admin support (backwards compatibility)
[[redirects]]
  from = "/admin/config.yml"
  to = "/.netlify/functions/config"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# API endpoints
[[redirects]]
  from = "/api/posts"
  to = "/.netlify/functions/posts"
  status = 200
  force = true

[[redirects]]
  from = "/api/post"
  to = "/.netlify/functions/post"
  status = 200
  force = true

[[redirects]]
  from = "/api/debug"
  to = "/.netlify/functions/debug"
  status = 200
  force = true

[[redirects]]
  from = "/api/movies"
  to = "/.netlify/functions/movies"
  status = 200
  force = true

[[redirects]]
  from = "/api/movie"
  to = "/.netlify/functions/movie"
  status = 200
  force = true

[[redirects]]
  from = "/api/tmdb"
  to = "/.netlify/functions/tmdb-search"
  status = 200
  force = true

# Serve blog pages
[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
