[build]
  publish = "public"
  command = "npm install && npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "16"

[[functions]]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["gray-matter", "@netlify/functions"]
  included_files = ["content/**"]

# Netlify Identity is handled automatically by Netlify
[identity]
  enable = true
  invite_only = true

# Redirects
[[redirects]]
  from = "/#invite_token=*"
  to = "/admin/#invite_token=:splat"
  status = 301
  force = true

# Use dynamic config.yml from function - MUST be before the general admin redirect
[[redirects]]
  from = "/admin/config.yml"
  to = "/.netlify/functions/config"
  status = 200
  force = true

# Admin redirects (general rule comes AFTER specific rules)
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# API endpoints
[[redirects]]
  from = "/api/posts"
  to = "/.netlify/functions/posts"
  status = 200
  force = true

[[redirects]]
  from = "/api/debug"
  to = "/.netlify/functions/debug"
  status = 200
  force = true

# Serve blog pages
[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
