[build]
  publish = "public"
  command = "npm run build"

# Netlify Identity is handled automatically by Netlify

# Redirect for identity tokens to admin page
[[redirects]]
  from = "/#invite_token=*"
  to = "/admin/#invite_token=:splat"
  status = 301
  force = true

# Admin redirects
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Serve blog pages
[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Use dynamic config.yml from function
[[redirects]]
  from = "/admin/config.yml"
  to = "/.netlify/functions/config"
  status = 200

[build.environment]
  NODE_VERSION = "16"

[functions]
  directory = "functions"

# Enable Netlify Identity but only allow invite-based signups
[identity]
  enable = true
  invite_only = true
