backend:
  name: test-repo
  # No branch needed for test-repo

# Media files will be stored in the repo under images/uploads
media_folder: "images/uploads"
public_folder: "/images/uploads"

# Publish mode configuration
# Comment out the line below to disable the editorial workflow
# publish_mode: editorial_workflow

# Collection for blog posts
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { label: "HTML Content", name: "html_content", widget: "markdown" }
      - { label: "Published At", name: "published_at", widget: "datetime" }
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "categories"
        search_fields: ["name"]
        value_field: "slug"
        display_fields: ["name"]
        required: false
      - label: "Tags"
        name: "tags"
        widget: "relation"
        collection: "tags"
        search_fields: ["name"]
        value_field: "slug"
        display_fields: ["name"]
        multiple: true
        required: false
      - label: "Authors"
        name: "authors"
        widget: "relation"
        collection: "authors"
        search_fields: ["name"]
        value_field: "slug"
        display_fields: ["name"]
        multiple: true
        required: false

  - name: "categories"
    label: "Categories"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }

  - name: "tags"
    label: "Tags"
    folder: "content/tags"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }

  - name: "authors"
    label: "Authors"
    folder: "content/authors"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Image URL", name: "image_url", widget: "image", required: false }
      - { label: "Website", name: "website", widget: "string", required: false }
      - { label: "Twitter", name: "twitter", widget: "string", required: false }
      - { label: "Bio", name: "bio", widget: "text", required: false }
